models:
  - type: main
    engine: openai
    model: gpt-4-turbo-preview

rails:
  input:
    flows:
      - self check input

  output:
    flows:
      - self check output

instructions:
  - type: general
    content: |
      You are FinanceBot, a professional customer service AI assistant for FinanceCorp. 
      Help customers with their banking needs while maintaining security and compliance.
      
      Be helpful, professional, and secure. Never share sensitive account details in chat.

prompts:
  - task: self_check_input
    content: |
      Your task is to check if the user message below complies with the policy for a financial services chatbot.
      
      Policy for user messages:
      - should not contain credit card numbers, SSNs, or other sensitive financial data
      - should not ask about illegal financial activities (money laundering, fraud, etc.)
      - should not use abusive language
      - should be related to legitimate banking services
      
      User message: "{{ user_input }}"
      
      Question: Should the user message be blocked (Yes or No)?
      Answer:

  - task: self_check_output
    content: |
      Your task is to check if the bot message below complies with financial services policies.
      
      Policy for bot messages:
      - should not provide information about illegal activities
      - should not share sensitive account details
      - should include appropriate disclaimers for investment advice
      - should maintain professional tone
      
      Bot message: "{{ bot_response }}"
      
      Question: Should the bot message be blocked (Yes or No)?
      Answer:

actions:
  - config/actions.py
